apiVersion: v1
kind: Service
metadata:
  name: "webhook-server"
  namespace:  {{ .Release.Namespace }}
spec:
  selector:
    name: xap-operator
  ports:
    - port: 8443
      targetPort: webhook-api

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "{{ .Release.Name }}-{{ .Release.Namespace }}-webhook"
  namespace:  {{ .Release.Namespace }}
  {{- if not .Values.webhook.ca }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}-cert-manager-webhook
  {{- end }}
webhooks:
  - name: "webhook-server.{{ .Release.Namespace }}.svc"
    objectSelector:
      matchLabels:
        manager: "{{ .Values.manager.name }}"
        gsAntiAffinity: "true"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      {{- if .Values.webhook.ca }}
      caBundle: {{ .Values.webhook.ca  | quote }}
      {{- end }}
      service:
        namespace: "{{ .Release.Namespace }}"
        name: "webhook-server"
        path: /webhook
        port: 8443
