{
 "title": "BBW-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Space",
    "label": "Space",
    "query": "SHOW TAG VALUES FROM \"space_data_data-types\" WITH KEY  = \"pu_name\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div>\n   <img alt=\"Spaceboard\" src=\"https://cdn-fsly.yottaa.net/5d669b394f1bbf7cb77826ae/www.bathandbodyworks.com/v~4b.21a/on/demandware.static/Sites-BathAndBodyWorks-Site/-/default/dw9932316d/images/svg-icons/Logos-main.svg?yocs=w_A_\" width=450\">\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "options": {
    "content": "<hr style=\"height: 5px; background-color: #2596be\">"
   }
  },
  {
   "title": "Total memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT SUM(val) FROM (SELECT last(value) as val FROM \"jvm_memory_heap_used-bytes\" WHERE $timeFilter AND pu_name != '' GROUP BY \"pu_instance_id\")"
    }
   ]
  },
  {
   "title": "Entries per object type",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_data_type_short_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "data_type_short_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_data_data-types",
     "query": "SELECT SUM(val) FROM (SELECT last(value) as val FROM \"space_data_data-types\"  WHERE (\"space_active\" = 'true' AND \"data_type_name\" != 'java.lang.Object' AND $timeFilter )  GROUP BY data_type_name, pu_instance_id) where val != 0 GROUP BY data_type_short_name, space_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "data_type_name", "operator": "!=", "value": "java.lang.Object" },
      { "condition": "AND", "key": "data_type_short_name", "operator": "!=", "value": "Value" }
     ]
    }
   ]
  },
  {
   "title": "GSCs CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<hr style=\"height: 5px; background-color: #2596be\">"
   }
  },
  {
   "title": "IOPS (Total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_operations_read-tp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_operations_write-tp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "alias": "take",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_operations_take-tp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "alias": "change",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_operations_change-tp",
     "query": "SELECT sum(\"value\") FROM \"space_operations_change-tp\" WHERE (\"space_name\" =~ /^$Space$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "alias": "execute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_operations_execute-tp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "alias": "update",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_operations_update-tp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS (Reads)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_operations_read-tp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    }
   ]
  },
  {
   "title": "IOPS (Writes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "2s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_operations_write-tp",
     "query": "SELECT sum(\"value\") FROM \"space_operations_update-tp\" WHERE (\"space_name\" =~ /^$Space$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "space_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<hr style=\"height: 5px; background-color: #2596be\">"
   }
  },
  {
   "title": "Instances table",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_instance_id" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "process_cpu_used-percent",
     "query": "SELECT  last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"pu_name\" = 'space') AND $timeFilter GROUP BY time($__interval), \"pu_instance_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_instance_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_memory_heap_used-percent",
     "query": "SELECT  last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"pu_name\" = 'space') AND $timeFilter GROUP BY time($__interval), \"pu_instance_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RAM" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_instance_id" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT  last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"pu_name\" = 'space') AND $timeFilter GROUP BY time($__interval), \"pu_instance_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_instance_id" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT count(\"value\") AS \"Status\" FROM \"jvm_uptime\" WHERE (\"pu_name\" =~ /^$Space$/) AND $timeFilter GROUP BY time(5m), \"pu_instance_id\", \"host\" ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_instance_id" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "space_primary" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "space_data_data-types",
     "query": "SELECT  last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"pu_name\" = 'space') AND $timeFilter GROUP BY time($__interval), \"pu_instance_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication Redo Log Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "alias": "Instance: $tag_pu_instance_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_instance_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_replication_redo-log_size",
     "query": "SELECT sum(value) FROM \"space_replication_redo-log_size\" WHERE space_name='demo' AND space_active='true' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "=~", "value": "/^$Space$/" }
     ]
    }
   ]
  }
 ]
}