CREATE TABLE "BBW_DEMO.EMPLOYEES" (
    EMP_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    PHONE_NUMBER VARCHAR(40),
    ADDRESS VARCHAR(100),
    IS_MANAGER CHAR(1),
    DEPARTMENT_CODE CHAR(1),
    COMMENTS CHAR(30)
)
