CREATE TABLE "BBW.EMPLOYEES" (
    EMP_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    PHONE_NUMBER VARCHAR(40),
    ADDRESS VARCHAR(100),
    IS_MANAGER VARCHAR(1),
    DEPARTMENT_CODE VARCHAR(1),
    COMMENTS VARCHAR(30)
)
