# Default values for kafka-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: kafka-ui
autoscaling:
  enabled: true
replicaCount: 1

image:
  repository: redpandadata/console
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v2.3.1

service:
  type: ClusterIP
resources: {}


