{{- if (include "flink.nodeLocalMode" .) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
status: {}
{{- end }}
