apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spacedeck.fullname" . }}
  labels:
    {{- include "spacedeck.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spacedeck.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spacedeck.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "spacedeck.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "spacedeck.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: IDLE_SESSION_TIMEOUT
            value: '30'
          - name: INSTALLATION
            value: {{ .Values.global.installation  | quote }}
          - name: INSTALLATION_VERSION
            value: {{ .Values.image.tag | default .Chart.AppVersion }}
          - name: AUTH_API_URL
            value: {{ .Values.auth_url  | quote }}
          - name: API_URL
            value: {{ .Values.api_url  | quote }}
          - name: DI_MANAGER_API_URL
            value: {{ .Values.di_manager_url  | quote }}
          - name: DI_MDM_API_URL
            value: {{ .Values.di_mdm_url  | quote }}
          - name: MCS_API_URL
            value: {{ .Values.creator_url  | quote }}
          - name: ZOOKEEPER_HOST
            value: {{ .Values.zookeeper_url  | quote }}
          {{- if .Values.global.security.enabled }}
          - name: AUTH
            value: "on"
          {{- end }}
          {{- if or (.Values.global.minio.enabled) (.Values.global.s3.enabled) }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                {{- if .Values.global.minio.enabled }}
                name: {{ .Values.global.minio.tenantName }}-user-1
                optional: false
                {{- else }}
                name: {{ .Values.s3.secretName }}
                optional: true
                {{- end }}
                {{- if .Values.global.minio.enabled }}
                key: CONSOLE_ACCESS_KEY
                {{- else }}
                key: ACCESS_KEY
                {{- end }}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                {{- if .Values.global.minio.enabled }}
                name: {{ .Values.global.minio.tenantName }}-user-1
                optional: false
                {{- else }}
                name: {{ .Values.s3.secretName }}
                optional: true
                {{- end }}
                {{- if .Values.global.minio.enabled }}
                key: CONSOLE_SECRET_KEY
                {{- else }}
                key: SECRET_KEY
                {{- end }}
          {{- end }}
          {{- if .Values.env }}
{{ toYaml .Values.env | indent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
