# Default values for service-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: service-operator
autoscaling:
  enabled: true
replicaCount: 1


global:
  ingressHost:
  security:
    enabled: true
  xap:
    security:
      service:
        name: xap-security
        port: 9000
  imagePullSecrets:
    - myregistrysecret

qsvcAutoCleanup:
  enabled: true

image:
  repository: gigaspaces/mcs-service-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.13

service:
  type: ClusterIP
  port: 8080

operatorConfig:
  memoryLimit: 400Mi
  image: gigaspaces/mcs-query-service:1.0.15
  tokenServiceConfig:
    kid: common
    privateKeySecret: qs-private-key
    privateKeyPath: /opt/queryservice/key
resources: {}
