apiVersion: v2
appVersion: 16.4.0
dependencies:
- alias: di
  condition: di.enabled
  name: di
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 2.9.54
- alias: flink
  condition: flink.enabled
  name: di-flink
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 2.1.1
- alias: grafana
  condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.44.7
- alias: influxdb
  condition: metrics.enabled
  name: influxdb
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 4.9.14
- condition: kafka.enabled
  name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: 20.0.6
- alias: redpanda
  condition: redpanda.enabled
  name: kafka-ui
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 0.2.0
- alias: service-creator
  condition: service-creator.enabled
  name: service-creator
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 1.0.13
- alias: service-operator
  condition: service-operator.enabled
  name: service-operator
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 1.0.20
- alias: spacedeck
  condition: spacedeck.enabled
  name: spacedeck
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 1.1.39
- alias: manager
  condition: manager.enabled
  name: xap-manager
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 16.4.0
- alias: operator
  condition: operator.enabled
  name: xap-operator
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 16.4.0
- alias: dgw
  condition: dgw.enabled
  name: xap-dgw
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 16.4.0
- alias: iidrAS
  name: iidr-as
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  tags:
  - iidr
  version: 2.2.0
- alias: iidrKafka
  name: iidr-kafka
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  tags:
  - iidr
  version: 2.1.1
- alias: diSubscriptionManagerIidr
  name: di-subscription-manager
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  tags:
  - iidr
  version: 1.12.14
- alias: diSubscriptionManagerS3
  condition: global.s3.enabled
  name: di-subscription-manager
  repository: https://s3.amazonaws.com/resources.gigaspaces.com/helm-charts-dih
  version: 1.12.14
- alias: prometheus
  condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 22.6.0
- alias: minio-operator
  condition: global.minio.enabled
  name: operator
  repository: https://operator.min.io/
  version: 5.0.5
description: A Helm chart for DIH
name: dih
version: 16.4.0
