metric:
   enabled: true
manager:
   service:
      type: LoadBalancer
      api:
         enabled: true
         port: 8090
         nodePort:
      lus:
         enabled: true
         port: 4174
         nodePort:
      lrmi:
         enabled: true
         port: 8200
         nodePort:
   antiAffinity:
      enabled: true
   ha: true
   java:
      heap: limit-300Mi
   license: "Product=InsightEdge;Version=16.3;Type=ENTERPRISE;Customer=Gigaspaces_Demo_PROD;Expiration=2023-Dec-31;Hash=VQdZNeFX6EO6RaABKNR6"
license: "Product=InsightEdge;Version=16.3;Type=ENTERPRISE;Customer=Gigaspaces_Demo_PROD;Expiration=2023-Dec-31;Hash=VQdZNeFX6EO6RaABKNR6"

kafka: