apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spacedeck
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      proxy_ssl_server_name on;
      proxy_ssl_name $host;
spec:
  ingressClassName: spacedeck
  rules:
  - host: 
    http:
      paths:
      - backend:
          service:
            name: spacedeck
            port:
              number: 80
        path: /
        pathType: Prefix
