# Default values for service-creator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: service-creator
autoscaling:
  enabled: true
replicaCount: 1

image:
  repository: gigaspaces/mcs-service-creator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.13


service:
  type: ClusterIP
  port: 8080

resources: {}

ingress:
  nameOverride: "sc"
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /services/$1

global:
  ingressHost:
  security:
    enabled: true
  xap:
    security:
      service:
        name: xap-security
        port: 9000
  imagePullSecrets:
    - myregistrysecret
    -
security:
  authorityCheckUrl: "/oauth2/v1/authority-check"
